"use client";
import { motion } from "framer-motion";
import { TRANSITION_SMOOTH } from "@/shared/presentation/animations";
import { cn } from "@/shared/presentation/utils";
import { MEDIA_COSTS } from "@/config/media";

interface Props {
  readonly onYes: () => void;
  readonly onNo: () => void;
  /** Displayed tease text generated by the companion. */
  readonly offerLine?: string;
  readonly mediaType: "image" | "video";
  readonly characterImageUrl?: string | null;
  readonly characterName?: string;
  /** Credit cost (for display). Defaults from MEDIA_COSTS if not provided. */
  readonly cost?: number;
}

/**
 * OfferBubble — shown when the companion (via <<VA mode:offer>>) wants to
 * proactively offer a photo or video. Companion's tease text is in the normal
 * text bubble above; this just adds the Yes/No affordance.
 */
export function OfferBubble({ onYes, onNo, mediaType, offerLine, characterImageUrl, characterName, cost: costProp }: Props) {
  const cost = costProp ?? (mediaType === "video" ? MEDIA_COSTS.VIDEO : MEDIA_COSTS.IMAGE);

  return (
    <motion.div
      className="flex w-full justify-start"
      initial={{ opacity: 0, y: 12, filter: "blur(4px)" }}
      animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
      transition={TRANSITION_SMOOTH}
    >
      <div className="flex max-w-[75%] flex-col gap-2">
        {characterImageUrl ? (
          <div className="h-6 w-6 overflow-hidden rounded-full border border-[#2a2a34] shrink-0">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={characterImageUrl} alt={characterName ?? ""} className="h-full w-full object-cover" />
          </div>
        ) : null}

        <div className="rounded-2xl rounded-bl-md bg-[#1a1a22] px-4 py-3 space-y-3">
          {offerLine ? (
            <p className="text-sm text-white/95 italic">{offerLine}</p>
          ) : (
            <p className="text-sm text-white/95 italic">
              Want me to send you a {mediaType}?
            </p>
          )}
          <div className="flex gap-2">
            <button
              type="button"
              onClick={onYes}
              className={cn(
                "flex-1 rounded-full py-1.5 text-xs font-semibold transition-colors",
                "bg-gradient-to-r from-pink-500 to-rose-500 text-white hover:from-pink-600 hover:to-rose-600",
              )}
            >
              Yes, send me one · {cost} cr
            </button>
            <button
              type="button"
              onClick={onNo}
              className={cn(
                "flex-1 rounded-full py-1.5 text-xs font-medium transition-colors",
                "bg-[#252530] text-[#8a8a99] hover:bg-[#2d2d3a] hover:text-white",
              )}
            >
              Maybe later
            </button>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
